on: push
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.TOC_ACCESS_TOKEN }}
          CREATE_PR: true
          MAX_HEADER_LEVEL:  3
      
